w4d2/twitter/config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'

  resources :tweets, only: [:index, :new, :create, :edit, :update]
end

w4d2/twitter/app/models/hash_tag.rb
# == Schema Information
#
# Table name: hash_tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class HashTag < ActiveRecord::Base
  has_many :hash_taggings,
    class_name: 'HashTagging',
    primary_key: :id,
    foreign_key: :hash_tag_id
end

w4d2/twitter/app/models/hash_tagging.rb
# == Schema Information
#
# Table name: hash_taggings
#
#  id          :integer          not null, primary key
#  tweet_id    :integer
#  hash_tag_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class HashTagging < ActiveRecord::Base
  belongs_to :hash_tag,
    class_name: 'HashTag',
    primary_key: :id,
    foreign_key: :hash_tag_id

  belongs_to :tweet,
    class_name: 'Tweet',
    primary_key: :id,
    foreign_key: :tweet_id
end

w4d2/twitter/app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id   :integer          not null, primary key
#  name :string
#

class Location < ActiveRecord::Base
  has_many(:users,
      {
        class_name: 'User',
        primary_key: :id,
        foreign_key: :location_id
      }
    )

  has_many :tweets,
    through: :users,
    source: :authored_tweets
end

w4d2/twitter/app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  body       :string
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Tweet < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user,
    class_name: 'User',
    primary_key: :id,
    foreign_key: :user_id

  has_many :hash_taggings,
    class_name: 'HashTagging',
    primary_key: :id,
    foreign_key: :tweet_id

  has_many :hash_tags,
    through: :hash_taggings,
    source: :hash_tag
  # this through association relies on direct associtions
  # it should go after the direct associations
end

w4d2/twitter/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id          :integer          not null, primary key
#  name        :string
#  location_id :integer
#

class User < ActiveRecord::Base
  belongs_to :location,
    class_name: 'Location',
    primary_key: :id,
    foreign_key: :location_id
  # user has foreign_key, so it holds the belongs_to association
  # belongs to is a method

  has_many :tweets,
    class_name: 'Tweet',
    primary_key: :id,
    foreign_key: :user_id
end

w4d2/twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def this_will_be_available_in_all_controllers
    puts 'hi'
  end

  def current_user
    # helpful for user auth -- stay tuned
  end
end

w4d2/twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.order('updated_at DESC').includes(:user)

    # render json: tweets
    render :index
  end

  def new
    @tweet = Tweet.new

    render :new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user = User.all.sample # probably not what you want to do

    if tweet.save
      redirect_to tweets_url
    else
      render json: tweet.errors, status: 422 # unprocessable entity
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])

    render :edit
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update(tweet_params)
      redirect_to tweets_url
    else
      render json: @tweet.errors, status: 422
    end
  end

  private

  def tweet_params
    # params: { tweet: { body: "love wins"} }
    params.require(:tweet).permit(:body)
  end
end

w4d2/twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d2/twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

w4d2/twitter/app/views/tweets/_form.html.erb
<% url = persisted ? tweet_url(tweet) : tweets_url %>
<% button_text = persisted ? "Update Tweet" : "Create Tweet" %>

<form action="<%= url %>" method="POST">
  <% if persisted %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <!-- this will be sent to our server as tweet: {body: ""} -->
  <label for="body">Body:</label>
  <input id="body" type="text" name="tweet[body]" value="<%= tweet.body %>">

  <!-- clicking this submits the entire form -->
  <input type="submit" value="<%= button_text %>">
</form>

w4d2/twitter/app/views/tweets/_tweet.html.erb
<li>
  <%= tweet.body %>
  - <%= tweet.user.name %>
</li>

w4d2/twitter/app/views/tweets/edit.html.erb
<h1>Update a Tweet!</h1>

<%= render "form", tweet: @tweet, persisted: true %>

w4d2/twitter/app/views/tweets/index.html.erb
<h1>All the Tweets!</h1>

<ul>
  <!--
    here we're rendering the _tweet partial
    for each tweet in @tweets
  -->
  <%= render @tweets %>
</ul>

w4d2/twitter/app/views/tweets/new.html.erb
<h1>Create a Tweet!</h1>

<%= render 'form', tweet: @tweet, persisted: false %>